### ISSUE TITLE
Provide some example files

### ISSUE THREAD

**Issue by lehkost** [dracor-org/ezlinavis#3]

**Comment by cmil** [comment]
The following example files would require issue #2 to be solved:

[Benito Pérez Galdós - Electra (1901).txt](https://github.com/dlina/ezlinavis/files/1031714/Benito.Perez.Galdos.-.Electra.1901.txt)
[Leo Tolstoy - The Power of Darkness, 1st variant (1887).txt](https://github.com/dlina/ezlinavis/files/1031715/Leo.Tolstoy.-.The.Power.of.Darkness.1st.variant.1887.txt)

**Comment by cmil** [comment]
Examples have been implemented with PR #7 and deployed on https://hashtable.de/ezlinavis/.

**Comment by lehkost** [comment]
Looking great!
