### ISSUE TITLE
Graph rendering in Firefox

### ISSUE THREAD

**Issue by lehkost** [dracor-org/ezlinavis#9]
I see two problems when starting *ezlinavis* in Firefox:
1. The graph seems to be placed in the vertical centre of the CSV column. If this list is long, the graph doesn't show before scrolling down (maybe it's enough to top-align the graph?).
2. The graph-layout algorithm seems to work differently in Firefox, if you compare the graphs for "Faust, pt. 1" in Firefox and Chrome. The latter, although always a bit differently of course, usually shows nice clusters around Faust. In Firefox, the graph looks like a haystack. Why could the two browsers show different results?

**Comment by cmil** [comment]
The above commit fixes the csv column. I cannot, however, see a significant difference in rendering the graph between FF (54.0.1) and Chrome on macOS. Could you provide screenshots?

**Comment by lehkost** [comment]
This is what Chrome renders (nice separation of the two main clusters, the actual play and the [Walpurgisnachtstraum](https://de.wikipedia.org/wiki/Walpurgisnachtstraum), a scene completely detached from the main graph):
![faust-canvas-chrome](https://user-images.githubusercontent.com/6539515/28668512-7271753e-72d0-11e7-9873-8fec4962f45d.png)

This is what Firefox does (for the same play, "Faust, pt. 1"):
![faust-canvas-firefox](https://user-images.githubusercontent.com/6539515/28668516-7a7daca2-72d0-11e7-9a93-f28b313c32fc.png)

But I guess we can close this issue since the underlying data is correct and can be taken to dedicated graph-rendering software via the CSV file.
